<h4>Encoding Categorical variables:-</h4>
<p>It is a way of converting categorical data into numerical representations 
that can be used in a machine learning model.</p>

In [18]:
import pandas as pd 

In [23]:
#Using the Dictionary(sets) and list data structure in DataFrame
df = pd.DataFrame({"col1": ["Sun", "Sun", "Moon", "Earth", "Moon", "Venus"]})
print("The original data")
print(df)

#Taking 30 Star[*]
print("*" * 30)

#The Python library Pandas provides a function called 'get_dummies' to enable one-hot encoding.
#The parameter 'prefix' indicates the 'prefix' of the new column name.
df_new = pd.get_dummies(df, columns=["col1"], prefix="Planet")
print("The transform data using get_dummies")
print(df_new)

The original data
    col1
0    Sun
1    Sun
2   Moon
3  Earth
4   Moon
5  Venus
******************************
The transform data using get_dummies
   Planet_Earth  Planet_Moon  Planet_Sun  Planet_Venus
0             0            0           1             0
1             0            0           1             0
2             0            1           0             0
3             1            0           0             0
4             0            1           0             0
5             0            0           0             1


In [12]:
ids = [11, 22, 33, 44, 55, 66, 77]
countries = ['Seattle', 'London', 'Lahore', 'Berlin', 'Abuja']

 #Here we have a Pandas dataframe called df with two lists: 'ids' and 'Cities'
df = pd.DataFrame(list(zip(ids, countries)),columns=['Ids', 'Cities'])
print(df)

   Ids   Cities
0   11  Seattle
1   22   London
2   33   Lahore
3   44   Berlin
4   55    Abuja


In [21]:
df = pd.DataFrame({"col1": ["Seattle", "London", "Lahore", "Berlin", "Abuja"]})
print("The original data")
print(df)

print("*" * 30)


df_new = pd.get_dummies(df, columns=["col1"], prefix="Cities")
print("The transform data using get_dummies")
print(df_new)

The original data
      col1
0  Seattle
1   London
2   Lahore
3   Berlin
4    Abuja
******************************
The transform data using get_dummies
   Cities_Abuja  Cities_Berlin  Cities_Lahore  Cities_London  Cities_Seattle
0             0              0              0              0               1
1             0              0              0              1               0
2             0              0              1              0               0
3             0              1              0              0               0
4             1              0              0              0               0


In [11]:
#Join two Tuples together
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a, b)
print(tuple(x))

(('John', 'Jenny'), ('Charles', 'Christy'), ('Mike', 'Monica'))


In [25]:
'''We can implement a similar functionality with Sklearn,
which provides an object/function for one-hot encoding in the preprocessing module'''

import sklearn.preprocessing as preprocessing
import numpy as np
import pandas as pd

targets = np.array(["red", "green", "blue", "yellow", "pink",
                    "white"])
#We use LabelEncoder to convert the string to int on line 7 and line 8.
labelEnc = preprocessing.LabelEncoder()
new_target = labelEnc.fit_transform(targets)

#Line 9 creates our OneHotEncoder object.
onehotEnc = preprocessing.OneHotEncoder()

#Line 10 fits the original feature using fit().
onehotEnc.fit(new_target.reshape(-1, 1))

#Line 11 converts the original feature to the new feature using one-hot encoding.
targets_trans = onehotEnc.transform(new_target.reshape(-1, 1))
print("The original data")
print(targets)
print("The transform data using OneHotEncoder")

#You can see the new data from the output of line 15.
print(targets_trans.toarray())

The original data
['red' 'green' 'blue' 'yellow' 'pink' 'white']
The transform data using OneHotEncoder
[[0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [26]:
#Let’s see the OneHotEncoder class in action with another example. First, here’s how to import the class.
from sklearn.preprocessing import OneHotEncoder 

In [27]:
#Like before, we first populate our list of unique values for the encoder.
x = [[11, "Seattle"], [22, "London"], [33, "Lahore"], [44, "Berlin"], [55, "Abuja"]]
y = OneHotEncoder().fit_transform(x).toarray()
#When we print this, we get the following for our now encoded values:
print(y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]]


In [ ]:
Reference:https://www.educative.io/blog/one-hot-encoding